src/Secretary/urls.py
from django.urls import path, include
from .views import (
    InstructorListView,
    InstructorDetailView,
    InstructorCreateView,
    InstructorUpdateView,
    InstructorDeleteView,

    StudentCreateView,
    StudentListView,
    StudentDetailView,
    StudentUpdateView,
    StudentDeleteView,

    EventCreateView,
    EventListView,
    EventDetailView,
    EventUpdateView,
    EventDeleteView,

    CourseListView,
    CourseCreateView
)
from . import views


app_name = 'secretary'
urlpatterns = [
    path('', views.index, name='home'),
    path('planning/', include([
        path('', views.planning_filter),
        path('appointment/', include([
            path('create/', EventCreateView.as_view(), name='appointment-create'),
            path('', EventListView.as_view(), name='appointment-list'),
            path('<int:pk>/', EventDetailView.as_view(), name='appointment-detail'),
            path('<int:pk>/update/', EventUpdateView.as_view(), name='appointment-update'),
            path('<int:pk>/delete/', EventDeleteView.as_view(), name='appointment-delete'),
        ]))

    ])),
    path('instructor/', include([
        path('create/', InstructorCreateView.as_view(), name="instructor-create"),
        path('', InstructorListView.as_view(), name='instructor-list'),
        path('<int:pk>/', InstructorDetailView.as_view(), name='instructor-detail'),
        path('<int:pk>/update/', InstructorUpdateView.as_view(), name='instructor-update'),
        path('<int:pk>/delete/', InstructorDeleteView.as_view(), name='instructor-delete'),
    ])),
    path('student/', include([
        path('create/', StudentCreateView.as_view(), name="student-create"),
        path('', StudentListView.as_view(), name='student-list'),
        path('<int:pk>/', StudentDetailView.as_view(), name='student-detail'),
        path('<int:pk>/update/', StudentUpdateView.as_view(), name='student-update'),
        path('<int:pk>/delete/', StudentDeleteView.as_view(), name='student-delete'),
    ])),
    path('course/', include([
        path('', CourseListView.as_view(), name='course-list'),
        path('<int:pk>/', views.detail_course, name='course-detail'),
        path('create/', CourseCreateView.as_view(), name="course-create"),
    ]))

]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Student.urls')),
    path('secretary/', include('Secretary.urls')),
    path('instructor/', include('instructor.urls')),
    path('planning/', include('planning.urls')),
]

src/instructor/urls.py
from django.urls import path, include
from .views import (
    StudentEventCreateView,
    StudentEventCreateView,
    StudentEventDeleteView
)
from . import views


app_name ='instructor'
urlpatterns = [
    path('', views.index),

    path('planning/', include([
        path('', views.planning_filter_student),
        path('appointment/', include([
            path('', views.student_planning),
            path('create/', StudentEventCreateView.as_view(), name="appointment-create"),
            path('<int:pk>/update/', StudentEventCreateView.as_view(), name='appointment-update'),
            path('<int:pk>/delete/', StudentEventDeleteView.as_view(), name='appointment-delete'),
        ]))
    ])),

    path('student/', include([
        path('detail/', views.student_detail),
    ]))
]

src/planning/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.calendar_index)
]

src/instructor/models.py
from django.db import models

# Create your models here.

src/planning/models.py
from django.db import models
from users.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
from colorfield.fields import ColorField


class Event(models.Model):

    start = models.DateTimeField('start', db_index=True)
    end   = models.DateTimeField('end', db_index=True, help_text="The end time must be later than the start time.")
    title = models.CharField('title', max_length=255)
    description = RichTextField("description", blank=True)
    creator = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="creator",
        related_name='snippets'
    )
    person = models.OneToOneField(User,
        blank=True,
        verbose_name="person",
        on_delete=models.CASCADE
    )
    created_on = models.DateTimeField("created on", auto_now_add=True)
    updated_on = models.DateTimeField("updated on", auto_now=True)
    color_event = ColorField("Color event", blank=True, max_length=10, default='#FFC0CB')
    address = models.CharField(max_length=255, blank=True)

    def get_absolute_url(self):
        return reverse('secretary:appointment-detail',kwargs={'pk':self.pk})

    class Meta:
        verbose_name = "event"
        verbose_name_plural = "events"
        index_together = (("start", "end"),)

    def __str__(self):
        return self.title

src/instructor/views.py
from django.shortcuts import render
from users.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from planning.models import Event

from django.core import serializers
from django.http import JsonResponse

from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


def index(request):
    return render(request, 'instructor/home-list.html', locals())

#------------------------------------------------------------------------------[ USER-PLANNING ]-----------------------------------------------------------------#
@login_required
def planning_filter_student(request):

    if request.user.is_instructor == True:
        events = Event.objects.filter(creator=request.user.id)
        qs_json = serializers.serialize('json', events)

    return render(request, 'instructor/planning/calendar/index.html', locals())


@login_required
def student_detail(request):

    user_contains = request.GET.get('user_search')
    users = User.objects.filter(Q(username=user_contains))

    return render(request, 'instructor/student/detail.html', locals())


@login_required
def student_planning(request):
    events = Event.objects.filter(person=request.user.id)
    return render(request, 'instructor/planning/event/read-list.html', locals())


class StudentEventCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    model = Event
    fields = '__all__'
    template_name = 'secretary/planning/event/create.html'
    success_message = f' The event has been created'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class StudentEventUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = Event
    fields = '__all__'
    template_name = 'secretary/planning/event/update.html'
    success_message = f' The event has been updated'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class StudentEventDeleteView(DeleteView):

    model = Event
    template_name = 'secretary/planning/event/delete.html'
    success_url = '/instructor/planning/appointment/'

src/planning/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import JsonResponse

from .models import Event


def calendar_index(request):
    events = Event.objects.all()
    qs_json = serializers.serialize('json', events)
    return render(request, 'planning/home-list.html', locals())

src/instructor/templates/instructor/planning/event/create.html
{% extends 'layout/default.html' %}
{% load crispy_forms_tags %}

{% block body-content %}
<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Create appointment</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit" name="button">create</button>
    </div>
  </form>
</div>
{% endblock %}

src/instructor/templates/instructor/planning/event/delete.html
{% extends 'layout/default.html' %}

{% block body-content %}
<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Delete appointment</legend>
      <h2 class="font-weight-light"> Are you sure you want to delete this user : appointment {{ object.username }} </h2>
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-danger" type="submit" name="button">Yes, delete</button>
      <a class="btn btn-outline-secondary" href="{% url 'secretary:appointment-detail' object.id %}">Cancel</a>
    </div>
  </form>
</div>
{% endblock %}

src/instructor/templates/instructor/planning/event/read-list.html
{% extends 'layout/default.html' %}

{% block body-content %}

<a class="btn btn-info" href="{% url 'instructor:appointment-create' %}">ADD NEW</a>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">title</th>
      <th scope="col">color</th>
      <th scope="col">start</th>
      <th scope="col">end</th>
      <th scope="col">created</th>
      <th scope="col">edit</th>
      <th scope="col">delete</th>
    </tr>
  </thead>
  <tbody>
    {% for planning in events %}
          <tr>
            <th scope="row">{{ planning.id }}</th>
            <th>{{ planning.title }}</th>
            <td>{{ planning.color_event }}</td>
            <td>{{ planning.start }}</td>
            <td>{{ planning.end }}</td>
            {% if planning.creator.is_instructor == True %}

              <td>{{ planning.creator }} - (instructor)</td>
              {% elif planning.creator.is_student == True %}
              <td>{{ planning.creator }} - (student)</td>

            {% endif %}
            
            <td><a href="{% url 'instructor:appointment-update' pk=planning.id %}">edit</a></td>
            <td><a href="{% url 'instructor:appointment-delete' pk=planning.id %}">delete</a></td>
          </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

src/instructor/templates/instructor/planning/event/update.html
{% extends 'layout/default.html' %}
{% load crispy_forms_tags %}

{% block body-content %}
<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Create instructor</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit" name="button">update</button>
    </div>
  </form>
</div>
{% endblock %}