src/Secretary/urls.py
from django.urls import path, include
from .views import (
    InstructorListView,
    InstructorDetailView,
    InstructorCreateView,
    InstructorUpdateView,
    InstructorDeleteView,

    StudentCreateView,
    StudentListView,
    StudentDetailView,
    StudentUpdateView,
    StudentDeleteView,

    EventCreateView,
    EventListView,
    EventDetailView,
    EventUpdateView,
    EventDeleteView,

    CourseListView,
    CourseCreateView
)
from . import views


app_name = 'secretary'
urlpatterns = [
    path('', views.index, name='home'),
    path('planning/', include([
        path('', views.planning_filter),
        path('appointment/', include([
            path('create/', EventCreateView.as_view(), name='appointment-create'),
            path('', EventListView.as_view(), name='appointment-list'),
            path('<int:pk>/', EventDetailView.as_view(), name='appointment-detail'),
            path('<int:pk>/update/', EventUpdateView.as_view(), name='appointment-update'),
            path('<int:pk>/delete/', EventDeleteView.as_view(), name='appointment-delete'),
        ]))

    ])),
    path('instructor/', include([
        path('create/', InstructorCreateView.as_view(), name="instructor-create"),
        path('', InstructorListView.as_view(), name='instructor-list'),
        path('<int:pk>/', InstructorDetailView.as_view(), name='instructor-detail'),
        path('<int:pk>/update/', InstructorUpdateView.as_view(), name='instructor-update'),
        path('<int:pk>/delete/', InstructorDeleteView.as_view(), name='instructor-delete'),
    ])),
    path('student/', include([
        path('create/', StudentCreateView.as_view(), name="student-create"),
        path('', StudentListView.as_view(), name='student-list'),
        path('<int:pk>/', StudentDetailView.as_view(), name='student-detail'),
        path('<int:pk>/update/', StudentUpdateView.as_view(), name='student-update'),
        path('<int:pk>/delete/', StudentDeleteView.as_view(), name='student-delete'),
    ])),
    path('course/', include([
        path('', CourseListView.as_view(), name='course-list'),
        path('<int:pk>/', views.detail_course, name='course-detail'),
        path('create/', CourseCreateView.as_view(), name="course-create"),
    ]))

]

src/Student/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index),
    path('planning/', views.student_planning)
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Student.urls')),
    path('secretary/', include('Secretary.urls')),
    path('instructor/', include('instructor.urls')),
    path('planning/', include('planning.urls')),
]

src/Secretary/models.py
from django.db import models
from users.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse


class Course(models.Model):

    course_name = models.CharField(max_length=255)
    course_code = models.CharField(blank=True, max_length=255, null=True)
    course_details = RichTextField()

    start = models.DateTimeField('start', db_index=True, blank=True, null=True)
    end = models.DateTimeField('end', blank=True, null=True)
    course_time = models.TimeField(blank=True, null=True)
    course_price = models.IntegerField(blank=True, null=True)
    instructor = models.ForeignKey(User, on_delete=models.CASCADE)

    course_photo = models.ImageField(default='secretary/courses/default.png', upload_to='courses/', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('secretary:course-list')

    def __str__(self):
        return self.course_name

src/Student/models.py
from django.db import models
from Secretary.models import Course
from users.models import User


class Subscription(models.Model):

    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    valid = models.BooleanField(default=False, null=True)

    def __str__(self):
        return self.user.username

src/users/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import AbstractUser

from phone_field import PhoneField
from ckeditor.fields import RichTextField


GENDER_CHOICES = (
    (0, 'male'),
    (1, 'female'),
    (2, 'not specified'),
)

class User(AbstractUser):

    is_secretary  = models.BooleanField(default=False)
    is_instructor = models.BooleanField(default=False)
    is_student    = models.BooleanField(default=False)

    def get_absolute_url(self):
        if self.is_instructor == True:
            return reverse('secretary:instructor-detail',kwargs={'pk': self.pk})
        elif self.is_student == True:
            return reverse('secretary:student-detail',kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('secretary:instructor-update',kwargs={'pk':self.pk})

    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'

    def __str__(self):
        return self.username

class Secretary(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username



class Student(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    gender = models.IntegerField(choices=GENDER_CHOICES, default=2)
    phone = PhoneField(blank=True, help_text='Contact phone number')
    birthday = models.DateField(blank=True, null=True)
    address = models.CharField(max_length=255)
    avatar = models.ImageField(default='user/Student/default.png', upload_to='user/', null=True, blank=True)

    def __str__(self):
        return self.user.username


class Instructor(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    gender = models.IntegerField(choices=GENDER_CHOICES, default=2)
    phone = PhoneField(blank=True, help_text='Contact phone number')
    birthday = models.DateField(blank=True, null=True)
    address = models.CharField(max_length=255, blank=True)
    avatar = models.ImageField(default='user/Instructor/default.png', upload_to='user/', null=True, blank=True)
    bio = RichTextField(blank=True)

    def greet(self):
        gender = self.get_gender_display()
        if gender == 'male':
            return 'Hi, boy.'
        elif gender == 'female':
            return 'Hello, girl.'
        else:
            return 'Hey there, user!'

    def __str__(self):
        return self.user.username

src/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from users.models import User, Instructor

from ckeditor.widgets import CKEditorWidget


class UserRegisterForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email','password1', 'password2', 'is_secretary', 'is_instructor', 'is_student']


# class InstructorForm(forms.ModelForm):
#
#     class Meta:
#         model = Instructor
#         fields = ('bio','address')

src/Secretary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
    FormView
)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.db.models import Q
from users.models import User
from planning.models import Event
from Secretary.models import Course
from Student.models import Subscription

from users.forms import UserRegisterForm

from django.core import serializers
from django.http import JsonResponse
import stripe

stripe.api_key = "sk_test_T28WIocgbLEBrnuoAZ6P4R7000vjrtYfb3"


def index(request):
    return render(request, 'secretary/home-list.html', locals())


#------------------------------------------------------------------------------[ USER-INSTRUCTOR ]-----------------------------------------------------------------#
class InstructorCreateView(LoginRequiredMixin, SuccessMessageMixin, FormView):

    template_name = 'secretary/user/instructor/create.html'
    form_class = UserRegisterForm
    success_message = f' The user account has been created'
    success_url = '/secretary/instructor/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class InstructorListView(LoginRequiredMixin, ListView):

    model = User
    template_name = 'secretary/user/instructor/read-list.html'
    context_object_name = 'users_form'
    ordering = ['-date_joined']


class InstructorDetailView(DetailView):

    model = User
    template_name = 'secretary/user/instructor/read-detail.html'


class InstructorUpdateView(LoginRequiredMixin,UpdateView):

    model = User
    template_name = 'secretary/user/instructor/update.html'
    fields = ['first_name', 'last_name', 'username', 'email']
    context_object_name = 'form'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class InstructorDeleteView(DeleteView):

    model = User
    template_name = 'secretary/user/instructor/delete.html'
    success_url = '/secretary/instructor/'


#------------------------------------------------------------------------------[ USER-STUDENT ]-----------------------------------------------------------------#
class StudentCreateView(LoginRequiredMixin, SuccessMessageMixin, FormView):

    template_name = 'secretary/user/student/create.html'
    form_class = UserRegisterForm
    success_message = f' The user account has been created'
    success_url = '/secretary/student/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class StudentListView(LoginRequiredMixin, ListView):

    model = User
    template_name = 'secretary/user/student/read-list.html'
    context_object_name = 'users_form'
    ordering = ['-date_joined']


class StudentDetailView(DetailView):

    model = User
    template_name = 'secretary/user/student/read-detail.html'


class StudentUpdateView(LoginRequiredMixin,UpdateView):

    model = User
    template_name = 'secretary/user/student/update.html'
    fields = ['first_name', 'last_name', 'username', 'email']
    context_object_name = 'form'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class StudentDeleteView(DeleteView):

    model = User
    template_name = 'secretary/user/student/delete.html'
    success_url = '/secretary/student/'


#------------------------------------------------------------------------------[ USER-PLANNING-EVENT ]-----------------------------------------------------------------#
class EventCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    model = Event
    fields = '__all__'
    template_name = 'secretary/planning/event/create.html'
    success_message = f' The event has been created'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class EventListView(LoginRequiredMixin, ListView):

    model = Event
    template_name = 'secretary/planning/event/read-list.html'
    context_object_name = 'planning_form'
    ordering = ['-start']


class EventDetailView(DetailView):

    model = Event
    template_name = 'secretary/planning/event/read-detail.html'


class EventUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = Event
    fields = '__all__'
    template_name = 'secretary/planning/event/update.html'
    success_message = f' The event has been updated'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class EventDeleteView(DeleteView):

    model = Event
    template_name = 'secretary/planning/event/delete.html'
    success_url = '/secretary/appointment/'


#------------------------------------------------------------------------------[ USER-PLANNING ]-----------------------------------------------------------------#
@login_required
def planning_filter(request):
    qs = Event.objects.all()
    user_contains = request.GET.get('user_search')

    try:
        users = User.objects.filter(Q(username=user_contains)).distinct()
    except User.DoesNotExist:
        users = None

    if not users:
        events = qs.filter()
    else:
        for user in users:
            events = qs.filter(creator=user.id)

    qs_json = serializers.serialize('json', events)
    return render(request, 'secretary/planning/calendar/index.html', locals())


#------------------------------------------------------------------------------[ COURSE ]-----------------------------------------------------------------#
class CourseCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    model = Course
    fields = '__all__'
    template_name = 'secretary/course/create.html'
    success_message = f' The event has been created'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class CourseListView(LoginRequiredMixin, ListView):

    model = Course
    template_name = 'secretary/course/read-list.html'
    context_object_name = 'course_form'
    # ordering = ['-start']

@login_required
def detail_course(request, pk):
    course = get_object_or_404(Course, id=pk)

    if request.method == 'POST':

        customer = stripe.Customer.create(
            email=request.user.email,
            name=request.user,
            source=request.POST.get('stripeToken')
        )

        charge = stripe.Charge.create(
            customer=customer,
            amount=course.course_price*100,
            currency='usd',
            description=course.course_name,
        )

        Subscription.objects.create(course=course, user=request.user, valid=True)
        messages.success(request, f'thank you for purchasing our course')

        return redirect('secretary:course-list')

    return render(request, 'secretary/course/read-detail.html', locals())

src/Student/views.py
from django.shortcuts import render
from users.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from planning.models import Event

from django.core import serializers
from django.http import JsonResponse, HttpResponse


def index(request):
    return render(request, 'student/home-list.html', locals())


@login_required
def student_planning(request):

    if request.user.is_student == True:
        events = Event.objects.filter(creator=request.user.id)
        qs_json = serializers.serialize('json', events)

    return render(request, 'student/planning/calendar/index.html', locals())

src/users/views.py
from django.shortcuts import render

# Create your views here.

src/Secretary/templates/secretary/user/student/create.html
{% extends 'layout/default.html' %}
{% load crispy_forms_tags %}

{% block body-content %}
<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Create student</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit" name="button">create</button>
    </div>
  </form>
</div>
{% endblock %}

src/Secretary/templates/secretary/user/student/delete.html
{% extends 'layout/default.html' %}

{% block body-content %}
<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Delete student</legend>
      <h2 class="font-weight-light"> Are you sure you want to delete this user : student - username {{ object.username }} </h2>
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-danger" type="submit" name="button">Yes, delete</button>
      <a class="btn btn-outline-secondary" href="{% url 'secretary:instructor-detail' object.id %}">Cancel</a>
    </div>
  </form>
</div>
{% endblock %}

src/Secretary/templates/secretary/user/student/read-detail.html
{% extends 'layout/default.html' %}

{% block body-content %}
<div class="container">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  <a class="btn btn-info" href="{% url 'secretary:student-create' %}">Ajouter</a>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">username</th>
        <th scope="col">Email</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% if user.is_superuser != True and user.is_student == True %}
        <tr>
          <th scope="row">{{ object.id }}</th>
          <td>{{ object.username }}</td>
          <td>{{ object.email }}</td>
          <td><a href="{% url 'secretary:student-update' pk=object.id %}">edit</a></td>
          <td><a href="{% url 'secretary:student-delete' pk=object.id %}">delete</a></td>
        </tr>
      {% endif %}
    </tbody>
  </table>
</div>
{% endblock %}

src/Secretary/templates/secretary/user/student/read-list.html
{% extends 'layout/default.html' %}

{% block body-content %}
<div class="container">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  <a class="btn btn-info" href="{% url 'secretary:student-create' %}">ADD NEW</a>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">username</th>
        <th scope="col">Email</th>
        <th scope="col">Details</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users_form %}
          {% if user.is_superuser != True and user.is_student == True %}
            <tr>
              <th scope="row">{{ user.id }}</th>
              <td>{{ user.username }}</td>
              <td>{{ user.email }}</td>
              <td><a href="{% url 'secretary:student-detail' pk=user.id %}">read</a></td>
              <td><a href="{% url 'secretary:student-update' pk=user.id %}">edit</a></td>
              <td><a href="{% url 'secretary:student-delete' pk=user.id %}">delete</a></td>
            </tr>
          {% endif %}
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}