src/Secretary/urls.py
from django.urls import path, include
from .views import (
    InstructorListView,
    InstructorDetailView,
    InstructorCreateView,
    InstructorUpdateView,
    InstructorDeleteView,

    StudentCreateView,
    StudentListView,
    StudentDetailView,
    StudentUpdateView,
    StudentDeleteView,

    EventCreateView,
    EventListView,
    EventDetailView,
    EventUpdateView,
    EventDeleteView,

    CourseListView,
    CourseCreateView
)
from . import views


app_name = 'secretary'
urlpatterns = [
    path('', views.index, name='home'),
    path('planning/', include([
        path('', views.planning_filter),
        path('appointment/', include([
            path('create/', EventCreateView.as_view(), name='appointment-create'),
            path('', EventListView.as_view(), name='appointment-list'),
            path('<int:pk>/', EventDetailView.as_view(), name='appointment-detail'),
            path('<int:pk>/update/', EventUpdateView.as_view(), name='appointment-update'),
            path('<int:pk>/delete/', EventDeleteView.as_view(), name='appointment-delete'),
        ]))

    ])),
    path('instructor/', include([
        path('create/', InstructorCreateView.as_view(), name="instructor-create"),
        path('', InstructorListView.as_view(), name='instructor-list'),
        path('<int:pk>/', InstructorDetailView.as_view(), name='instructor-detail'),
        path('<int:pk>/update/', InstructorUpdateView.as_view(), name='instructor-update'),
        path('<int:pk>/delete/', InstructorDeleteView.as_view(), name='instructor-delete'),
    ])),
    path('student/', include([
        path('create/', StudentCreateView.as_view(), name="student-create"),
        path('', StudentListView.as_view(), name='student-list'),
        path('<int:pk>/', StudentDetailView.as_view(), name='student-detail'),
        path('<int:pk>/update/', StudentUpdateView.as_view(), name='student-update'),
        path('<int:pk>/delete/', StudentDeleteView.as_view(), name='student-delete'),
    ])),
    path('course/', include([
        path('', CourseListView.as_view(), name='course-list'),
        path('<int:pk>/', views.detail_course, name='course-detail'),
        path('create/', CourseCreateView.as_view(), name="course-create"),
    ]))

]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Student.urls')),
    path('secretary/', include('Secretary.urls')),
    path('instructor/', include('instructor.urls')),
    path('planning/', include('planning.urls')),
]

src/planning/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.calendar_index)
]

src/Secretary/models.py
from django.db import models
from users.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse


class Course(models.Model):

    course_name = models.CharField(max_length=255)
    course_code = models.CharField(blank=True, max_length=255, null=True)
    course_details = RichTextField()

    start = models.DateTimeField('start', db_index=True, blank=True, null=True)
    end = models.DateTimeField('end', blank=True, null=True)
    course_time = models.TimeField(blank=True, null=True)
    course_price = models.IntegerField(blank=True, null=True)
    instructor = models.ForeignKey(User, on_delete=models.CASCADE)

    course_photo = models.ImageField(default='secretary/courses/default.png', upload_to='courses/', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('secretary:course-list')

    def __str__(self):
        return self.course_name

src/planning/models.py
from django.db import models
from users.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
from colorfield.fields import ColorField


class Event(models.Model):

    start = models.DateTimeField('start', db_index=True)
    end   = models.DateTimeField('end', db_index=True, help_text="The end time must be later than the start time.")
    title = models.CharField('title', max_length=255)
    description = RichTextField("description", blank=True)
    creator = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="creator",
        related_name='snippets'
    )
    person = models.OneToOneField(User,
        blank=True,
        verbose_name="person",
        on_delete=models.CASCADE
    )
    created_on = models.DateTimeField("created on", auto_now_add=True)
    updated_on = models.DateTimeField("updated on", auto_now=True)
    color_event = ColorField("Color event", blank=True, max_length=10, default='#FFC0CB')
    address = models.CharField(max_length=255, blank=True)

    def get_absolute_url(self):
        return reverse('secretary:appointment-detail',kwargs={'pk':self.pk})

    class Meta:
        verbose_name = "event"
        verbose_name_plural = "events"
        index_together = (("start", "end"),)

    def __str__(self):
        return self.title

src/Secretary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
    FormView
)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.db.models import Q
from users.models import User
from planning.models import Event
from Secretary.models import Course
from Student.models import Subscription

from users.forms import UserRegisterForm

from django.core import serializers
from django.http import JsonResponse
import stripe

stripe.api_key = "sk_test_T28WIocgbLEBrnuoAZ6P4R7000vjrtYfb3"


def index(request):
    return render(request, 'secretary/home-list.html', locals())


#------------------------------------------------------------------------------[ USER-INSTRUCTOR ]-----------------------------------------------------------------#
class InstructorCreateView(LoginRequiredMixin, SuccessMessageMixin, FormView):

    template_name = 'secretary/user/instructor/create.html'
    form_class = UserRegisterForm
    success_message = f' The user account has been created'
    success_url = '/secretary/instructor/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class InstructorListView(LoginRequiredMixin, ListView):

    model = User
    template_name = 'secretary/user/instructor/read-list.html'
    context_object_name = 'users_form'
    ordering = ['-date_joined']


class InstructorDetailView(DetailView):

    model = User
    template_name = 'secretary/user/instructor/read-detail.html'


class InstructorUpdateView(LoginRequiredMixin,UpdateView):

    model = User
    template_name = 'secretary/user/instructor/update.html'
    fields = ['first_name', 'last_name', 'username', 'email']
    context_object_name = 'form'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class InstructorDeleteView(DeleteView):

    model = User
    template_name = 'secretary/user/instructor/delete.html'
    success_url = '/secretary/instructor/'


#------------------------------------------------------------------------------[ USER-STUDENT ]-----------------------------------------------------------------#
class StudentCreateView(LoginRequiredMixin, SuccessMessageMixin, FormView):

    template_name = 'secretary/user/student/create.html'
    form_class = UserRegisterForm
    success_message = f' The user account has been created'
    success_url = '/secretary/student/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class StudentListView(LoginRequiredMixin, ListView):

    model = User
    template_name = 'secretary/user/student/read-list.html'
    context_object_name = 'users_form'
    ordering = ['-date_joined']


class StudentDetailView(DetailView):

    model = User
    template_name = 'secretary/user/student/read-detail.html'


class StudentUpdateView(LoginRequiredMixin,UpdateView):

    model = User
    template_name = 'secretary/user/student/update.html'
    fields = ['first_name', 'last_name', 'username', 'email']
    context_object_name = 'form'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class StudentDeleteView(DeleteView):

    model = User
    template_name = 'secretary/user/student/delete.html'
    success_url = '/secretary/student/'


#------------------------------------------------------------------------------[ USER-PLANNING-EVENT ]-----------------------------------------------------------------#
class EventCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    model = Event
    fields = '__all__'
    template_name = 'secretary/planning/event/create.html'
    success_message = f' The event has been created'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class EventListView(LoginRequiredMixin, ListView):

    model = Event
    template_name = 'secretary/planning/event/read-list.html'
    context_object_name = 'planning_form'
    ordering = ['-start']


class EventDetailView(DetailView):

    model = Event
    template_name = 'secretary/planning/event/read-detail.html'


class EventUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = Event
    fields = '__all__'
    template_name = 'secretary/planning/event/update.html'
    success_message = f' The event has been updated'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class EventDeleteView(DeleteView):

    model = Event
    template_name = 'secretary/planning/event/delete.html'
    success_url = '/secretary/appointment/'


#------------------------------------------------------------------------------[ USER-PLANNING ]-----------------------------------------------------------------#
@login_required
def planning_filter(request):
    qs = Event.objects.all()
    user_contains = request.GET.get('user_search')

    try:
        users = User.objects.filter(Q(username=user_contains)).distinct()
    except User.DoesNotExist:
        users = None

    if not users:
        events = qs.filter()
    else:
        for user in users:
            events = qs.filter(creator=user.id)

    qs_json = serializers.serialize('json', events)
    return render(request, 'secretary/planning/calendar/index.html', locals())


#------------------------------------------------------------------------------[ COURSE ]-----------------------------------------------------------------#
class CourseCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    model = Course
    fields = '__all__'
    template_name = 'secretary/course/create.html'
    success_message = f' The event has been created'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class CourseListView(LoginRequiredMixin, ListView):

    model = Course
    template_name = 'secretary/course/read-list.html'
    context_object_name = 'course_form'
    # ordering = ['-start']

@login_required
def detail_course(request, pk):
    course = get_object_or_404(Course, id=pk)

    if request.method == 'POST':

        customer = stripe.Customer.create(
            email=request.user.email,
            name=request.user,
            source=request.POST.get('stripeToken')
        )

        charge = stripe.Charge.create(
            customer=customer,
            amount=course.course_price*100,
            currency='usd',
            description=course.course_name,
        )

        Subscription.objects.create(course=course, user=request.user, valid=True)
        messages.success(request, f'thank you for purchasing our course')

        return redirect('secretary:course-list')

    return render(request, 'secretary/course/read-detail.html', locals())

src/planning/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import JsonResponse

from .models import Event


def calendar_index(request):
    events = Event.objects.all()
    qs_json = serializers.serialize('json', events)
    return render(request, 'planning/home-list.html', locals())

src/Secretary/templates/secretary/planning/event/read-detail.html
{% extends 'layout/default.html' %}

{% block body-content %}
<div class="container">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">title</th>
        <th scope="col">color</th>
        <th scope="col">start</th>
        <th scope="col">end</th>
        <th scope="col">created</th>
        <th scope="col">edit</th>
        <th scope="col">delete</th>
      </tr>
    </thead>
    <tbody>
            <tr>
              <th scope="row">{{ object.id }}</th>
              <th>{{ object.title }}</th>
              <td>{{ object.color_event }}</td>
              <td>{{ object.start }}</td>
              <td>{{ object.end }}</td>
              {% if object.creator.is_instructor == True %}

                <td>{{ object.creator }} - (instructor)</td>
                {% elif object.creator.is_student == True %}
                <td>{{ object.creator }} - (student)</td>

              {% endif %}

              <!-- {% if object.person.is_instructor == True %}

                <td>{{ object.person }} - (instructor)</td>
                {% elif object.person.is_student == True %}
                <td>{{ object.person }} - (student)</td>

              {% endif %} -->
              <td><a href="{% url 'secretary:appointment-update' pk=object.id %}">edit</a></td>
              <td><a href="{% url 'secretary:appointment-delete' pk=object.id %}">delete</a></td>
            </tr>
    </tbody>
  </table>
</div>
{% endblock %}

src/Secretary/templates/secretary/planning/event/read-list.html
{% extends 'layout/default.html' %}

{% block body-content %}
<div class="container">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  <a class="btn btn-info" href="{% url 'secretary:appointment-create' %}">ADD NEW</a>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">title</th>
        <th scope="col">color</th>
        <th scope="col">start</th>
        <th scope="col">end</th>
        <th scope="col">created</th>
        <th scope="col">edit</th>
        <th scope="col">delete</th>
      </tr>
    </thead>
    <tbody>
      {% for planning in planning_form %}
            <tr>
              <th scope="row">{{ planning.id }}</th>
              <th>{{ planning.title }}</th>
              <td>{{ planning.color_event }}</td>
              <td>{{ planning.start }}</td>
              <td>{{ planning.end }}</td>
              {% if planning.creator.is_instructor == True %}

                <td>{{ planning.creator }} - (instructor)</td>
                {% elif planning.creator.is_student == True %}
                <td>{{ planning.creator }} - (student)</td>

              {% endif %}
              <!-- {% if planning.person.is_instructor == True %}

                <td>{{ planning.person }} - (instructor)</td>
                {% elif planning.person.is_student == True %}
                <td>{{ planning.person }} - (student)</td>

              {% endif %} -->
              <td><a href="{% url 'secretary:appointment-update' pk=planning.id %}">edit</a></td>
              <td><a href="{% url 'secretary:appointment-delete' pk=planning.id %}">delete</a></td>
            </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}