src/Secretary/urls.py
from django.urls import path, include
from .views import (
    InstructorListView,
    InstructorDetailView,
    InstructorCreateView,
    InstructorUpdateView,
    InstructorDeleteView,

    StudentCreateView,
    StudentListView,
    StudentDetailView,
    StudentUpdateView,
    StudentDeleteView,

    EventCreateView,
    EventListView,
    EventDetailView,
    EventUpdateView,
    EventDeleteView,

    CourseListView,
    CourseCreateView
)
from . import views


app_name = 'secretary'
urlpatterns = [
    path('', views.index, name='home'),
    path('planning/', include([
        path('', views.planning_filter),
        path('appointment/', include([
            path('create/', EventCreateView.as_view(), name='appointment-create'),
            path('', EventListView.as_view(), name='appointment-list'),
            path('<int:pk>/', EventDetailView.as_view(), name='appointment-detail'),
            path('<int:pk>/update/', EventUpdateView.as_view(), name='appointment-update'),
            path('<int:pk>/delete/', EventDeleteView.as_view(), name='appointment-delete'),
        ]))

    ])),
    path('instructor/', include([
        path('create/', InstructorCreateView.as_view(), name="instructor-create"),
        path('', InstructorListView.as_view(), name='instructor-list'),
        path('<int:pk>/', InstructorDetailView.as_view(), name='instructor-detail'),
        path('<int:pk>/update/', InstructorUpdateView.as_view(), name='instructor-update'),
        path('<int:pk>/delete/', InstructorDeleteView.as_view(), name='instructor-delete'),
    ])),
    path('student/', include([
        path('create/', StudentCreateView.as_view(), name="student-create"),
        path('', StudentListView.as_view(), name='student-list'),
        path('<int:pk>/', StudentDetailView.as_view(), name='student-detail'),
        path('<int:pk>/update/', StudentUpdateView.as_view(), name='student-update'),
        path('<int:pk>/delete/', StudentDeleteView.as_view(), name='student-delete'),
    ])),
    path('course/', include([
        path('', CourseListView.as_view(), name='course-list'),
        path('<int:pk>/', views.detail_course, name='course-detail'),
        path('create/', CourseCreateView.as_view(), name="course-create"),
    ]))

]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Student.urls')),
    path('secretary/', include('Secretary.urls')),
    path('instructor/', include('instructor.urls')),
    path('planning/', include('planning.urls')),
]

src/Secretary/models.py
from django.db import models
from users.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse


class Course(models.Model):

    course_name = models.CharField(max_length=255)
    course_code = models.CharField(blank=True, max_length=255, null=True)
    course_details = RichTextField()

    start = models.DateTimeField('start', db_index=True, blank=True, null=True)
    end = models.DateTimeField('end', blank=True, null=True)
    course_time = models.TimeField(blank=True, null=True)
    course_price = models.IntegerField(blank=True, null=True)
    instructor = models.ForeignKey(User, on_delete=models.CASCADE)

    course_photo = models.ImageField(default='secretary/courses/default.png', upload_to='courses/', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('secretary:course-list')

    def __str__(self):
        return self.course_name

src/Secretary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
    FormView
)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.db.models import Q
from users.models import User
from planning.models import Event
from Secretary.models import Course
from Student.models import Subscription

from users.forms import UserRegisterForm

from django.core import serializers
from django.http import JsonResponse
import stripe

stripe.api_key = "sk_test_T28WIocgbLEBrnuoAZ6P4R7000vjrtYfb3"


def index(request):
    return render(request, 'secretary/home-list.html', locals())


#------------------------------------------------------------------------------[ USER-INSTRUCTOR ]-----------------------------------------------------------------#
class InstructorCreateView(LoginRequiredMixin, SuccessMessageMixin, FormView):

    template_name = 'secretary/user/instructor/create.html'
    form_class = UserRegisterForm
    success_message = f' The user account has been created'
    success_url = '/secretary/instructor/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class InstructorListView(LoginRequiredMixin, ListView):

    model = User
    template_name = 'secretary/user/instructor/read-list.html'
    context_object_name = 'users_form'
    ordering = ['-date_joined']


class InstructorDetailView(DetailView):

    model = User
    template_name = 'secretary/user/instructor/read-detail.html'


class InstructorUpdateView(LoginRequiredMixin,UpdateView):

    model = User
    template_name = 'secretary/user/instructor/update.html'
    fields = ['first_name', 'last_name', 'username', 'email']
    context_object_name = 'form'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class InstructorDeleteView(DeleteView):

    model = User
    template_name = 'secretary/user/instructor/delete.html'
    success_url = '/secretary/instructor/'


#------------------------------------------------------------------------------[ USER-STUDENT ]-----------------------------------------------------------------#
class StudentCreateView(LoginRequiredMixin, SuccessMessageMixin, FormView):

    template_name = 'secretary/user/student/create.html'
    form_class = UserRegisterForm
    success_message = f' The user account has been created'
    success_url = '/secretary/student/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class StudentListView(LoginRequiredMixin, ListView):

    model = User
    template_name = 'secretary/user/student/read-list.html'
    context_object_name = 'users_form'
    ordering = ['-date_joined']


class StudentDetailView(DetailView):

    model = User
    template_name = 'secretary/user/student/read-detail.html'


class StudentUpdateView(LoginRequiredMixin,UpdateView):

    model = User
    template_name = 'secretary/user/student/update.html'
    fields = ['first_name', 'last_name', 'username', 'email']
    context_object_name = 'form'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class StudentDeleteView(DeleteView):

    model = User
    template_name = 'secretary/user/student/delete.html'
    success_url = '/secretary/student/'


#------------------------------------------------------------------------------[ USER-PLANNING-EVENT ]-----------------------------------------------------------------#
class EventCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    model = Event
    fields = '__all__'
    template_name = 'secretary/planning/event/create.html'
    success_message = f' The event has been created'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class EventListView(LoginRequiredMixin, ListView):

    model = Event
    template_name = 'secretary/planning/event/read-list.html'
    context_object_name = 'planning_form'
    ordering = ['-start']


class EventDetailView(DetailView):

    model = Event
    template_name = 'secretary/planning/event/read-detail.html'


class EventUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = Event
    fields = '__all__'
    template_name = 'secretary/planning/event/update.html'
    success_message = f' The event has been updated'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class EventDeleteView(DeleteView):

    model = Event
    template_name = 'secretary/planning/event/delete.html'
    success_url = '/secretary/appointment/'


#------------------------------------------------------------------------------[ USER-PLANNING ]-----------------------------------------------------------------#
@login_required
def planning_filter(request):
    qs = Event.objects.all()
    user_contains = request.GET.get('user_search')

    try:
        users = User.objects.filter(Q(username=user_contains)).distinct()
    except User.DoesNotExist:
        users = None

    if not users:
        events = qs.filter()
    else:
        for user in users:
            events = qs.filter(creator=user.id)

    qs_json = serializers.serialize('json', events)
    return render(request, 'secretary/planning/calendar/index.html', locals())


#------------------------------------------------------------------------------[ COURSE ]-----------------------------------------------------------------#
class CourseCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    model = Course
    fields = '__all__'
    template_name = 'secretary/course/create.html'
    success_message = f' The event has been created'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class CourseListView(LoginRequiredMixin, ListView):

    model = Course
    template_name = 'secretary/course/read-list.html'
    context_object_name = 'course_form'
    # ordering = ['-start']

@login_required
def detail_course(request, pk):
    course = get_object_or_404(Course, id=pk)

    if request.method == 'POST':

        customer = stripe.Customer.create(
            email=request.user.email,
            name=request.user,
            source=request.POST.get('stripeToken')
        )

        charge = stripe.Charge.create(
            customer=customer,
            amount=course.course_price*100,
            currency='usd',
            description=course.course_name,
        )

        Subscription.objects.create(course=course, user=request.user, valid=True)
        messages.success(request, f'thank you for purchasing our course')

        return redirect('secretary:course-list')

    return render(request, 'secretary/course/read-detail.html', locals())

src/Secretary/templates/secretary/course/create.html
{% extends 'layout/default.html' %}
{% load crispy_forms_tags %}

{% block body-content %}
<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Create instructor</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit" name="button">create</button>
    </div>
  </form>
</div>
{% endblock %}

src/Secretary/templates/secretary/course/read-detail.html
{% extends 'layout/default.html' %}

{% block body-content %}
{% block style %}
<style media="screen">
/**
* The CSS shown here will not be introduced in the Quickstart guide, but shows
* how you can use CSS to style your Element's container.
*/
.StripeElement {
box-sizing: border-box;

height: 40px;

padding: 10px 12px;

border: 1px solid transparent;
border-radius: 4px;
background-color: white;

box-shadow: 0 1px 3px 0 #e6ebf1;
-webkit-transition: box-shadow 150ms ease;
transition: box-shadow 150ms ease;
}

.StripeElement--focus {
box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
border-color: #fa755a;
}

.StripeElement--webkit-autofill {
background-color: #fefde5 !important;
}
</style>
{% endblock %}


<form class="container-fluid" method="post" id="payment-form">
  {% csrf_token %}
  <div class="form">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button>Submit Payment</button>
</form>

{% block scripts %}
<script type="text/javascript">
    // Create a Stripe client.
    var stripe = Stripe('pk_test_77M6bxJEEiYlY4S6JXuM5a5Y00dKzsUFfH');

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
    base: {
      color: '#32325d',
      fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
      fontSmoothing: 'antialiased',
      fontSize: '16px',
      '::placeholder': {
        color: '#aab7c4'
      }
    },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a'
    }
    };

    // Create an instance of the card Element.
    var card = elements.create('card', {style: style});

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');

    // Handle real-time validation errors from the card Element.
    card.addEventListener('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
    });

    // Handle form submission.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(card).then(function(result) {
      if (result.error) {
        // Inform the user if there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server.
        stripeTokenHandler(result.token);
      }
    });
    });

    // Submit the form with the token ID.
    function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    // Submit the form
    form.submit();
    }
</script>
{% endblock %}

{% endblock %}

src/Secretary/templates/secretary/course/read-list.html
{% extends 'layout/default.html' %}

{% block body-content %}
<div class="container">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  {% if user.is_secretary %}
    <a class="btn btn-info" href="{% url 'secretary:course-create' %}">ADD NEW</a>
  {% endif %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">title</th>
        <th scope="col">time</th>
        <th scope="col">price</th>
        <th scope="col">details</th>
      </tr>
    </thead>
    <tbody>
      {% for course in course_form %}
      <!-- {{ user.subscription.valid }} -->
        <tr>
          <th scope="row">{{ course.id }}</th>
          <td>{{ course.course_name }}</td>
          <td>{{ course.course_time }}</td>
          <td>{{ course.course_price }}$</td>
          <td>
            {% if user.subscription.valid == True %}
              <a class="">allready</a>
              {% else %}
              <a href="{% url 'secretary:course-detail' pk=course.id %}">read</a>
            {% endif %}
          </td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}